# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-04-03 11:56
from __future__ import unicode_literals

import datetime
import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counsellor',
            name='act_score',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='counsellor',
            name='email',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='counsellor',
            name='ethnicity',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='counsellor',
            name='gpa',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='counsellor',
            name='phone_number',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='counsellor',
            name='sat_score',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_login',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username'),
        ),
    ]
